version: '2'
 
services:
   db:
     image: mariadb 
     volumes:
       - ~/data:/var/lib/mysql
     restart: always
     container_name: "rdb"
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: {yourpwd} 
       MYSQL_DATABASE: users
       MYSQL_USER: mysql
       MYSQL_PASSWORD: {yourpwd} 

   redis1:
     image: evansking/redis
     restart: always
     volumes:
       - ~/share:/share
     container_name: "redis1"
     
   redis2:
     image: evansking/redis
     restart: always
     volumes:
       - ~/share:/share
     container_name: "redis2"
     
   redis3:
     image: evansking/redis
     restart: always
     volumes:
       - ~/share:/share
     container_name: "redis3"

   redis4:
     image: evansking/redis
     restart: always
     volumes:
       - ~/share:/share
     container_name: "redis4"

   zookeeper1:
     image: zookeeper:latest
     container_name: "zookeeper1"
     restart: always
     environment:
       ZOO_MY_ID: 1
       ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

   zookeeper2:
     image: zookeeper:latest
     container_name: "zookeeper2"
     restart: always
     environment:
       ZOO_MY_ID: 2 
       ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888


   zookeeper3:
     image: zookeeper:latest
     container_name: "zookeeper3"
     restart: always
     environment:
       ZOO_MY_ID: 3 
       ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

   kafka1:
     image: wurstmeister/kafka 
     container_name: "kafka1"
     restart: always
     depends_on:
       - zookeeper1
       - zookeeper2
       - zookeeper3
     ports:
       - "9092:9092"
     environment:
       KAFKA_BROKER_ID: 1 
       KAFKA_ADVERTISED_PORT: 9092
       KAFKA_ADVERTISED_HOST_NAME: kafka1 
       KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 

   kafka2:
     image: wurstmeister/kafka 
     container_name: "kafka2"
     restart: always
     depends_on:
       - zookeeper1
       - zookeeper2
       - zookeeper3
     ports:
       - "9093:9092"
     environment:
       KAFKA_BROKER_ID: 2 
       KAFKA_ADVERTISED_PORT: 9092
       KAFKA_ADVERTISED_HOST_NAME: kafka2 
       KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 

   kafka3:
     image: wurstmeister/kafka 
     container_name: "kafka3"
     restart: always
     depends_on:
       - zookeeper1
       - zookeeper2
       - zookeeper3
     ports:
       - "9094:9092"
     environment:
       KAFKA_BROKER_ID: 3 
       KAFKA_ADVERTISED_PORT: 9092
       KAFKA_ADVERTISED_HOST_NAME: kafka3 
       KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 

   dev:
     image: evansking/nodedev
     command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
     volumes:
       - ~/share:/share
       - ~/data:/data
     container_name: "dev"
     ports:
       - "3000:3000"
       - "80:8888"
     depends_on:
       - db
       - redis1
       - redis2
       - redis3
       - redis4
       - zookeeper1
       - zookeeper2
       - zookeeper3
       - kafka1
       - kafka2
       - kafka3
     links:
       - redis1:test1
       - redis2:test2
       - redis3:test3
       - redis4:test4
       - zookeeper1:zookeeper1
       - zookeeper2:zookeeper2
       - zookeeper3:zookeeper3
       - db:rdb
