version: '2'

services:
   db:
     image: mariadb 
     volumes:
       - ~/data:/var/lib/mysql
     restart: always
     container_name: "rdb"
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: {yourpwd} 
       MYSQL_DATABASE: users
       MYSQL_USER: mysql
       MYSQL_PASSWORD: {yourpwd} 

   redis1:
     image: evansking/redis
     volumes:
       - ~/share:/share
     container_name: "redis1"
     
   redis2:
     image: evansking/redis
     volumes:
       - ~/share:/share
     container_name: "redis2"
     
   redis3:
     image: evansking/redis
     volumes:
       - ~/share:/share
     container_name: "redis3"

   redis4:
     image: evansking/redis
     volumes:
       - ~/share:/share
     container_name: "redis4"
   dev:
     image: evansking/nodedev
     command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
     volumes:
       - ~/share:/share
       - ~/data:/data
     container_name: "dev"
     ports:
       - "3000:3000"
       - "80:8888"
     depends_on:
       - db
       - redis1
       - redis2
       - redis3
       - redis4
     links:
       - redis1:test1
       - redis2:test2
       - redis3:test3
       - redis4:test4
       - db:rdb
